LEAD_INGESTION_AGENT_OUTPUT_TOPIC = "lead_ingestion_agent_output"
LEAD_ROUTING_AGENT_OUTPUT_TOPIC = "lead_routing_agent_output"
ACTIVE_OUTREACH_AGENT_OUTPUT_TOPIC = "active_outreach_agent_output"
NURTURE_CAMPAIGN_AGENT_OUTPUT_TOPIC = "future_campaign_agent_output"